/*
  The purpose of this file is to create a very basic Express framework
  server that has 2 endpoints:
            one for a GET request and one for a POST request

  Author: Terry Goldsmith
  Adapted by: Alison & Natalie
*/

// set the port where the server listens for clients
const port = 4200;

// start the Express framework and make it accessible via the reference
const express = require("express");

// define the top level Express function
const server = express();

// enable the server to recognize JSON format
server.use(express.json());

// enable incoming "name":"value" pairs to be any type including arrays
server.use(express.urlencoded({ extended: true }));

/*
  The purpose of this function is to execute the instructions
  necessary: to allow a request from any origin to access this site's content;
  allow only GET and POST requests; and to only accept requests that include
  "Content-Type".

  this sets up restrictions / reduces restrictions

  req - request object generated by the HTTP event
  res - response object generated by the HTTP event
  next - predefined function used when request/response cycle is not terminated
*/
const allowCrossDomain = function (req, res, next) {
  // allow any origin
  res.header("Access-Control-Allow-Origin", "*");
  // allow any method
  res.header("Access-Control-Allow-Methods", "GET,POST");
  // accept only headers with Content-Type included
  res.header("Access-Control-Allow-Headers", "Content-Type");
  // since this middleware function does not terminate the request/response cycle
  // the next() function must be called to continue to the succeeding middleware function
  next();
};

// set domain characteristics defined above
server.use(allowCrossDomain); // executes the function allowCrossDomain that is defined above

/*
  Preset the anonymous function to be the function called whenever a POST
  request is received by this server at the endpoint
  http://ugdev.cs.smu.ca:port/postUserData
*/

/*
  The purpose of this ANONYMOUS function is to respond to a POST request with relative
  endpoint: /postUserData

  it only executes if the endpoint is accessed

  req - request object generated by the HTTP event
  res - response object generated by the HTTP event

  Author: Terry Goldsmith
*/

// Import the defaultData object from store.js
const { defaultData } = require('./store.js');

server.post("/postUserData", function (req, res) {
  // log the "value" in the "name":"value" pair received
  console.log("req.body:", req.body);

  // Define a new JSON object to be returned
  let userDataToUpload = req.body; // Using the request body directly

  // Access the response object via the reference
  // Set the associated status to success
  // Place your new JSON object into the response object
  // Return the response object which terminates the
  // request/response cycle so next() is not required
  return res.status(200).send(userDataToUpload);
});

/*
  Preset the anonymous function to be the function called whenever a GET
  request is received by this server at the endpoint
  http://ugdev.cs.smu.ca:port/getUserData
*/

/*
  The purpose of this function is to respond to a GET request with relative
  endpoint: /getUserData

  req - request object generated by the HTTP event
  res - response object generated by the HTTP event

  Author: Terry Goldsmith
*/
server.get("/getUserData", function (req, res) {
  // Define a new JSON object to be returned
  let userDataToDownload = defaultData;

  // Access the response object via the reference
  // Set the associated status to success (200 is good)
  // Place your new JSON object into the response object
  // Return the response object which terminates the
  // request/response cycle so next() is not required
  return res.status(200).send(userDataToDownload);
});

/*
  Preset the anonymous function to be the function called when the server
  starts listening on the defined port.
*/

/*
  The purpose of this function is to produce a message on the Node.js console,
  indicating the server has begun to listen for clients on a port.

  Author: Terry Goldsmith
*/
server.listen(port, function () {
  console.log("Listening on port " + port);
});
